language: java
jdk:
  - openjdk8

branches: # Travis CI를 어느 브랜치가 푸시될 때 수행할지 지정
  only:
    - main

 # Travis CI 서버의 Home
cache:  # Gradle을 통해 의존성을 받게 되면,
  # 이를 해당 디렉토리에 캐시하여, 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정함.
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:  # deploy 명령어가 실행되기 전에 수행된다.
  - zip -r bootpractice * # 현재 위치의 모든 파일을 bootpactice 이름으로 압축(zip)하겠다.
  - mkdir -p deploy # deploy라는 디렉토리를 Travis CI가 실행 중인 위치에서 생성
  - mv bootpractice.zip deploy/bootpractice.zip #이동

deploy: # s3로 파일 업로드 혹은 CodeDeploy로 배포 등 외부 서비스와 연동될 행위들을 선언
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: flex-springboot-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      all_branches: true

before_install:
  - chmod +x gradlew

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - jungahzzzang@gmail.com